In [1]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3
import warnings
warnings.filterwarnings('ignore') # Hides unnecessary seaborn warnings

# 1. Base Countries Dictionary (Full Complete List)
countries = [
    {"country": "United States", "iso_code": "USA", "latitude": 37.1, "longitude": -95.7, "region": "North America"},
    {"country": "Canada", "iso_code": "CAN", "latitude": 56.1, "longitude": -106.3, "region": "North America"},
    {"country": "Mexico", "iso_code": "MEX", "latitude": 23.6, "longitude": -102.5, "region": "Latin America"},
    {"country": "Brazil", "iso_code": "BRA", "latitude": -14.2, "longitude": -51.9, "region": "Latin America"},
    {"country": "Argentina", "iso_code": "ARG", "latitude": -38.4, "longitude": -63.6, "region": "Latin America"},
    {"country": "Colombia", "iso_code": "COL", "latitude": 4.6, "longitude": -74.1, "region": "Latin America"},
    {"country": "Chile", "iso_code": "CHL", "latitude": -35.7, "longitude": -71.5, "region": "Latin America"},
    {"country": "United Kingdom", "iso_code": "GBR", "latitude": 55.4, "longitude": -3.4, "region": "Europe"},
    {"country": "France", "iso_code": "FRA", "latitude": 46.2, "longitude": 2.2, "region": "Europe"},
    {"country": "Germany", "iso_code": "DEU", "latitude": 51.2, "longitude": 10.5, "region": "Europe"},
    {"country": "Italy", "iso_code": "ITA", "latitude": 41.9, "longitude": 12.6, "region": "Europe"},
    {"country": "Spain", "iso_code": "ESP", "latitude": 40.5, "longitude": -3.7, "region": "Europe"},
    {"country": "Norway", "iso_code": "NOR", "latitude": 60.5, "longitude": 8.5, "region": "Europe"},
    {"country": "Sweden", "iso_code": "SWE", "latitude": 60.1, "longitude": 18.6, "region": "Europe"},
    {"country": "Finland", "iso_code": "FIN", "latitude": 61.9, "longitude": 25.7, "region": "Europe"},
    {"country": "Russia", "iso_code": "RUS", "latitude": 61.5, "longitude": 105.3, "region": "Europe/Asia"},
    {"country": "China", "iso_code": "CHN", "latitude": 35.9, "longitude": 104.2, "region": "Asia"},
    {"country": "Japan", "iso_code": "JPN", "latitude": 36.2, "longitude": 138.3, "region": "Asia"},
    {"country": "India", "iso_code": "IND", "latitude": 20.6, "longitude": 78.9, "region": "Asia"},
    {"country": "Indonesia", "iso_code": "IDN", "latitude": -0.8, "longitude": 113.9, "region": "Asia"},
    {"country": "Singapore", "iso_code": "SGP", "latitude": 1.3, "longitude": 103.8, "region": "Asia"},
    {"country": "Thailand", "iso_code": "THA", "latitude": 15.9, "longitude": 101.0, "region": "Asia"},
    {"country": "Vietnam", "iso_code": "VNM", "latitude": 14.1, "longitude": 108.3, "region": "Asia"},
    {"country": "United Arab Emirates", "iso_code": "ARE", "latitude": 23.4, "longitude": 53.8, "region": "Middle East"},
    {"country": "Nigeria", "iso_code": "NGA", "latitude": 9.1, "longitude": 8.7, "region": "Africa"},
    {"country": "Kenya", "iso_code": "KEN", "latitude": -0.0, "longitude": 37.9, "region": "Africa"},
    {"country": "Egypt", "iso_code": "EGY", "latitude": 26.8, "longitude": 30.8, "region": "Africa"},
    {"country": "South Africa", "iso_code": "ZAF", "latitude": -30.6, "longitude": 22.9, "region": "Africa"},
    {"country": "Australia", "iso_code": "AUS", "latitude": -25.3, "longitude": 133.8, "region": "Oceania"},
    {"country": "New Zealand", "iso_code": "NZL", "latitude": -40.9, "longitude": 174.9, "region": "Oceania"},
    {"country": "Luxembourg", "iso_code": "LUX", "latitude": 49.8, "longitude": 6.1, "region": "Europe"},
    {"country": "Ireland", "iso_code": "IRL", "latitude": 53.4, "longitude": -8.2, "region": "Europe"},
    {"country": "Switzerland", "iso_code": "CHE", "latitude": 46.8, "longitude": 8.2, "region": "Europe"},
    {"country": "Denmark", "iso_code": "DNK", "latitude": 56.3, "longitude": 9.5, "region": "Europe"},
    {"country": "Netherlands", "iso_code": "NLD", "latitude": 52.1, "longitude": 5.3, "region": "Europe"},
    {"country": "Austria", "iso_code": "AUT", "latitude": 47.5, "longitude": 14.6, "region": "Europe"},
    {"country": "Belgium", "iso_code": "BEL", "latitude": 50.5, "longitude": 4.5, "region": "Europe"},
    {"country": "Iceland", "iso_code": "ISL", "latitude": 64.9, "longitude": -19.0, "region": "Europe"},
    {"country": "Qatar", "iso_code": "QAT", "latitude": 25.4, "longitude": 51.2, "region": "Middle East"},
    {"country": "Kuwait", "iso_code": "KWT", "latitude": 29.3, "longitude": 47.5, "region": "Middle East"},
    {"country": "Bahrain", "iso_code": "BHR", "latitude": 26.1, "longitude": 50.6, "region": "Middle East"},
    {"country": "Saudi Arabia", "iso_code": "SAU", "latitude": 23.9, "longitude": 45.1, "region": "Middle East"},
    {"country": "Israel", "iso_code": "ISR", "latitude": 31.0, "longitude": 35.0, "region": "Middle East"},
    {"country": "South Korea", "iso_code": "KOR", "latitude": 36.5, "longitude": 127.8, "region": "Asia"},
    {"country": "Hong Kong", "iso_code": "HKG", "latitude": 22.3, "longitude": 114.2, "region": "Asia"},
    {"country": "Taiwan", "iso_code": "TWN", "latitude": 23.7, "longitude": 121.0, "region": "Asia"},
    {"country": "Brunei", "iso_code": "BRN", "latitude": 4.5, "longitude": 114.7, "region": "Asia"},
    {"country": "Malta", "iso_code": "MLT", "latitude": 35.9, "longitude": 14.4, "region": "Europe"},
    {"country": "Cyprus", "iso_code": "CYP", "latitude": 35.1, "longitude": 33.4, "region": "Europe"},
    {"country": "Portugal", "iso_code": "PRT", "latitude": 39.4, "longitude": -8.2, "region": "Europe"},
    {"country": "Burundi", "iso_code": "BDI", "latitude": -3.4, "longitude": 29.9, "region": "Africa"},
    {"country": "Malawi", "iso_code": "MWI", "latitude": -13.3, "longitude": 34.3, "region": "Africa"},
    {"country": "Mozambique", "iso_code": "MOZ", "latitude": -18.7, "longitude": 35.5, "region": "Africa"},
    {"country": "Madagascar", "iso_code": "MDG", "latitude": -18.8, "longitude": 46.9, "region": "Africa"},
    {"country": "Central African Republic", "iso_code": "CAF", "latitude": 6.6, "longitude": 20.9, "region": "Africa"},
    {"country": "Niger", "iso_code": "NER", "latitude": 17.6, "longitude": 8.1, "region": "Africa"},
    {"country": "Mali", "iso_code": "MLI", "latitude": 17.6, "longitude": -3.9, "region": "Africa"},
    {"country": "Chad", "iso_code": "TCD", "latitude": 15.5, "longitude": 18.7, "region": "Africa"},
    {"country": "Liberia", "iso_code": "LBR", "latitude": 6.4, "longitude": -9.4, "region": "Africa"},
    {"country": "Sierra Leone", "iso_code": "SLE", "latitude": 8.5, "longitude": -11.8, "region": "Africa"},
    {"country": "Rwanda", "iso_code": "RWA", "latitude": -1.9, "longitude": 29.9, "region": "Africa"},
    {"country": "Uganda", "iso_code": "UGA", "latitude": 1.4, "longitude": 32.3, "region": "Africa"},
    {"country": "Ethiopia", "iso_code": "ETH", "latitude": 9.1, "longitude": 40.5, "region": "Africa"},
    {"country": "Tanzania", "iso_code": "TZA", "latitude": -6.4, "longitude": 34.9, "region": "Africa"},
    {"country": "Democratic Republic of Congo", "iso_code": "COD", "latitude": -4.0, "longitude": 21.8, "region": "Africa"},
    {"country": "Gambia", "iso_code": "GMB", "latitude": 13.4, "longitude": -15.3, "region": "Africa"},
    {"country": "Guinea-Bissau", "iso_code": "GNB", "latitude": 11.8, "longitude": -15.2, "region": "Africa"},
    {"country": "Togo", "iso_code": "TGO", "latitude": 8.6, "longitude": 0.8, "region": "Africa"},
    {"country": "Nepal", "iso_code": "NPL", "latitude": 28.4, "longitude": 84.1, "region": "Asia"},
    {"country": "Yemen", "iso_code": "YEM", "latitude": 15.6, "longitude": 48.5, "region": "Middle East"}
]
countries_df = pd.DataFrame(countries)

# 2. Fetch GDP via World Bank API
print("Fetching GDP Data from World Bank API...")

def fetch_gdp(iso_code):
    url = f"https://api.worldbank.org/v2/country/{iso_code}/indicator/NY.GDP.PCAP.CD?format=json&date=2022"
    
    try:
        response = requests.get(url, timeout=10)
        data = response.json()
        
        if len(data) > 1 and data[1] is not None and data[1][0]['value'] is not None:
            return {
                "iso_code": iso_code,
                "gdp_per_capita": data[1][0]['value']
            }
        
    except Exception as e:
        print(f"Could not fetch GDP for {iso_code}: {e}")
    
    return {
        "iso_code": iso_code,
        "gdp_per_capita": None
    }

gdp_results = []

for iso_code in countries_df["iso_code"]:
    gdp_results.append(fetch_gdp(iso_code))

gdp_df = pd.DataFrame(gdp_results)

print("GDP dataframe created")
display(gdp_df.head())

# 3. Hardcoded HDI Values to bypass broken API
print("Loading HDI Data directly...")
hdi_mapping = {
    "USA": 0.921, "CAN": 0.936, "MEX": 0.758, "BRA": 0.754, "ARG": 0.842, "COL": 0.752, "CHL": 0.855,
    "GBR": 0.929, "FRA": 0.903, "DEU": 0.942, "ITA": 0.895, "ESP": 0.905, "NOR": 0.961, "SWE": 0.947, 
    "FIN": 0.940, "RUS": 0.822, "CHN": 0.768, "JPN": 0.925, "IND": 0.633, "IDN": 0.705, "SGP": 0.939, 
    "THA": 0.800, "VNM": 0.703, "ARE": 0.911, "NGA": 0.535, "KEN": 0.575, "EGY": 0.731, "ZAF": 0.713, 
    "AUS": 0.951, "NZL": 0.931, "LUX": 0.930, "IRL": 0.945, "CHE": 0.962, "DNK": 0.948, "NLD": 0.941, 
    "AUT": 0.916, "BEL": 0.937, "ISL": 0.959, "QAT": 0.855, "KWT": 0.831, "BHR": 0.875, "SAU": 0.875, 
    "ISR": 0.919, "KOR": 0.925, "HKG": 0.952, "TWN": 0.926, "BRN": 0.829, "MLT": 0.918, "CYP": 0.896, 
    "PRT": 0.866, "BDI": 0.426, "MWI": 0.512, "MOZ": 0.446, "MDG": 0.501, "CAF": 0.404, "NER": 0.400, 
    "MLI": 0.428, "TCD": 0.394, "LBR": 0.481, "SLE": 0.477, "RWA": 0.534, "UGA": 0.525, "ETH": 0.498, 
    "TZA": 0.549, "COD": 0.479, "GMB": 0.500, "GNB": 0.483, "TGO": 0.539, "NPL": 0.602, "YEM": 0.455
}
hdi_data = [{"iso_code": iso, "hdi_value": val} for iso, val in hdi_mapping.items()]
hdi_df = pd.DataFrame(hdi_data)

print("Setup Complete! Data is ready.")

Fetching GDP Data from World Bank API...
GDP dataframe created

  iso_code  gdp_per_capita
0      USA    76657.248884
1      CAN    56256.800726
2      MEX    11405.794047
3      BRA     9281.332821
4      ARG    13962.189409

Loading HDI Data directly...
Setup Complete! Data is ready.

In [2]:
# Merge geography, GDP, and HDI datasets
merged_df = countries_df.merge(
    gdp_df,
    on="iso_code",
    how="left"
).merge(
    hdi_df,
    on="iso_code",
    how="left"
)

# Feature engineering: absolute latitude measures distance from the equator
merged_df["abs_latitude"] = merged_df["latitude"].apply(abs)

# Feature engineering: map regions to numeric IDs
region_map = {
    "North America": 1,
    "Latin America": 2,
    "Europe": 3,
    "Europe/Asia": 4,
    "Asia": 5,
    "Middle East": 6,
    "Africa": 7,
    "Oceania": 8
}

merged_df["region_id"] = merged_df["region"].map(region_map)

# Feature engineering: classify countries by climate zone
def assign_climate(lat):
    if lat <= 23.5:
        return "Tropical"
    elif lat <= 35:
        return "Subtropical"
    elif lat <= 60:
        return "Temperate"
    else:
        return "Cold"

merged_df["climate_zone"] = merged_df["abs_latitude"].apply(assign_climate)

# Preview final merged dataset
merged_df.head()

,country,iso_code,latitude,longitude,region,gdp_per_capita,hdi_value,abs_latitude,region_id,climate_zone
0,United States,USA,37.1,-95.7,North America,76657.248884,0.921,37.1,1,Temperate
1,Canada,CAN,56.1,-106.3,North America,56256.800726,0.936,56.1,1,Temperate
2,Mexico,MEX,23.6,-102.5,Latin America,11405.794047,0.758,23.6,2,Subtropical
3,Brazil,BRA,-14.2,-51.9,Latin America,9281.332821,0.754,14.2,2,Tropical
4,Argentina,ARG,-38.4,-63.6,Latin America,13962.189409,0.842,38.4,2,Temperate

## SQL Analysis

This section contains the required SQL queries for the final project. Each query includes comments explaining what it does, how it works, and why it matters to the analysis.

In [3]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("Final_v1.db")

In [4]:
merged_df.to_sql(
    "country_metrics",
    conn,
    if_exists="replace",
    index=False
)

70

In [5]:
pd.read_sql("""
-- Query 1: Preview country metrics table
-- Purpose: Confirm that the final dataset loaded into SQLite correctly.
-- Method: Select the first 10 rows from the country_metrics table.
-- Why: This gives a quick check that the SQL table contains the expected country-level data.

SELECT *
FROM country_metrics
LIMIT 10;
""", conn)

,country,iso_code,latitude,longitude,region,gdp_per_capita,hdi_value,abs_latitude,region_id,climate_zone
0,United States,USA,37.1,-95.7,North America,76657.248884,0.921,37.1,1,Temperate
1,Canada,CAN,56.1,-106.3,North America,56256.800726,0.936,56.1,1,Temperate
2,Mexico,MEX,23.6,-102.5,Latin America,11405.794047,0.758,23.6,2,Subtropical
3,Brazil,BRA,-14.2,-51.9,Latin America,9281.332821,0.754,14.2,2,Tropical
4,Argentina,ARG,-38.4,-63.6,Latin America,13962.189409,0.842,38.4,2,Temperate
5,Colombia,COL,4.6,-74.1,Latin America,6680.445069,0.752,4.6,2,Tropical
6,Chile,CHL,-35.7,-71.5,Latin America,15405.616577,0.855,35.7,2,Temperate
7,United Kingdom,GBR,55.4,-3.4,Europe,47057.043229,0.929,55.4,3,Temperate
8,France,FRA,46.2,2.2,Europe,40988.639641,0.903,46.2,3,Temperate
9,Germany,DEU,51.2,10.5,Europe,50506.517964,0.942,51.2,3,Temperate

In [6]:
pd.read_sql("""
-- Query 2: Check missing values in key fields
-- Purpose: Identify missing values in GDP, HDI, latitude, and climate zone.
-- Method: Use CASE WHEN statements to count missing values by column.
-- Why: Missing values can affect EDA, modeling, and conclusions.

SELECT
    SUM(CASE WHEN gdp_per_capita IS NULL THEN 1 ELSE 0 END) AS missing_gdp,
    SUM(CASE WHEN hdi_value IS NULL THEN 1 ELSE 0 END) AS missing_hdi,
    SUM(CASE WHEN latitude IS NULL THEN 1 ELSE 0 END) AS missing_latitude,
    SUM(CASE WHEN climate_zone IS NULL THEN 1 ELSE 0 END) AS missing_climate_zone
FROM country_metrics;
""", conn)

   missing_gdp  missing_hdi  missing_latitude  missing_climate_zone
0            2            0                 0                     0

In [7]:
pd.read_sql("""
-- Query 3: Check unique regions and climate zones
-- Purpose: Review the categorical variables used in the analysis.
-- Method: Count distinct regions and climate zones.
-- Why: This confirms that the dataset has meaningful geographic groupings for EDA.

SELECT
    COUNT(DISTINCT region) AS unique_regions,
    COUNT(DISTINCT climate_zone) AS unique_climate_zones
FROM country_metrics;
""", conn)

   unique_regions  unique_climate_zones
0               8                     4

In [8]:
pd.read_sql("""
-- Query 4: GDP and HDI summary by region
-- Purpose: Compare economic and development outcomes across regions.
-- Method: Group by region and calculate country count, average GDP, and average HDI.
-- Why: Regional comparisons help identify broad geographic patterns in development.

SELECT
    region,
    COUNT(*) AS country_count,
    AVG(gdp_per_capita) AS avg_gdp_per_capita,
    AVG(hdi_value) AS avg_hdi
FROM country_metrics
GROUP BY region
ORDER BY avg_gdp_per_capita DESC;
""", conn)

          region  country_count  avg_gdp_per_capita   avg_hdi
0  North America              2        66457.024805  0.928500
1         Europe             19        60108.698442  0.928421
2        Oceania              2        57134.614077  0.941000
3    Middle East              7        50562.228018  0.817286
4           Asia             12        25194.340047  0.808917
5    Europe/Asia              1        15619.614258  0.822000
6  Latin America              5        11347.075585  0.792200
7         Africa             22         1358.042160  0.505909

In [9]:
pd.read_sql("""
-- Query 5: GDP and HDI summary by climate zone
-- Purpose: Compare GDP and HDI across climate zones.
-- Method: Group by climate_zone and calculate average GDP and HDI.
-- Why: This directly connects to the project question about geography and development outcomes.

SELECT
    climate_zone,
    COUNT(*) AS country_count,
    AVG(gdp_per_capita) AS avg_gdp_per_capita,
    AVG(hdi_value) AS avg_hdi,
    AVG(abs_latitude) AS avg_abs_latitude
FROM country_metrics
GROUP BY climate_zone
ORDER BY avg_gdp_per_capita DESC;
""", conn)

  climate_zone  country_count  avg_gdp_per_capita   avg_hdi  avg_abs_latitude
0         Cold              5        61303.408166  0.925800         61.780000
1    Temperate             23        49756.872298  0.910261         44.295652
2  Subtropical             11        34134.238952  0.821455         26.736364
3     Tropical             31         9324.136110  0.584484         10.625806

In [10]:
pd.read_sql("""
-- Query 6: Join geography and development views
-- Purpose: Demonstrate how country geography connects to development outcomes.
-- Method: Create geography and development subqueries, then join them on iso_code.
-- Why: This separates geographic variables from development variables and recombines them for analysis.

SELECT
    g.country,
    g.region,
    g.climate_zone,
    g.abs_latitude,
    d.gdp_per_capita,
    d.hdi_value
FROM
    (
        SELECT iso_code, country, region, climate_zone, abs_latitude
        FROM country_metrics
    ) AS g
JOIN
    (
        SELECT iso_code, gdp_per_capita, hdi_value
        FROM country_metrics
    ) AS d
ON g.iso_code = d.iso_code
ORDER BY d.gdp_per_capita DESC
LIMIT 20;
""", conn)

,country,region,climate_zone,abs_latitude,gdp_per_capita,hdi_value
0,Luxembourg,Europe,Temperate,49.8,123719.658916,0.930
1,Norway,Europe,Cold,60.5,109269.520580,0.961
2,Ireland,Europe,Temperate,53.4,105190.685953,0.945
3,Switzerland,Europe,Temperate,46.8,94394.510680,0.962
4,Singapore,Asia,Tropical,1.3,90299.069464,0.939
5,Qatar,Middle East,Subtropical,25.4,88701.468976,0.855
6,United States,North America,Temperate,37.1,76657.248884,0.921
7,Iceland,Europe,Cold,64.9,76350.455042,0.959
8,Denmark,Europe,Temperate,56.3,67781.094094,0.948
9,Australia,Oceania,Subtropical,25.3,65169.519112,0.951
10,Netherlands,Europe,Temperate,52.1,59123.318556,0.941
11,Canada,North America,Temperate,56.1,56256.800726,0.936
12,Israel,Middle East,Subtropical,31.0,54949.621556,0.919
13,Sweden,Europe,Cold,60.1,54836.890724,0.947
14,Austria,Europe,Temperate,47.5,52336.772522,0.916
15,United Arab Emirates,Middle East,Tropical,23.4,50759.758923,0.911
16,Belgium,Europe,Temperate,50.5,50605.749668,0.937
17,Germany,Europe,Temperate,51.2,50506.517964,0.942
18,Finland,Europe,Cold,61.9,50440.560225,0.940
19,New Zealand,Oceania,Temperate,40.9,49099.709042,0.931

In [11]:
pd.read_sql("""
-- Query 7: Rank countries by GDP within region
-- Purpose: Identify the highest GDP countries within each region.
-- Method: Join geography and economic subqueries, then use RANK() over each region.
-- Why: Ranking within region gives a more meaningful peer comparison than global ranking alone.

SELECT
    g.country,
    g.region,
    e.gdp_per_capita,
    RANK() OVER (
        PARTITION BY g.region
        ORDER BY e.gdp_per_capita DESC
    ) AS regional_gdp_rank
FROM
    (
        SELECT iso_code, country, region
        FROM country_metrics
    ) AS g
JOIN
    (
        SELECT iso_code, gdp_per_capita
        FROM country_metrics
    ) AS e
ON g.iso_code = e.iso_code
ORDER BY g.region, regional_gdp_rank;
""", conn)

          country         region  gdp_per_capita  regional_gdp_rank
0    South Africa         Africa     6534.248678                  1
1           Egypt         Africa     4233.307837                  2
2         Nigeria         Africa     2899.160475                  3
3           Kenya         Africa     2109.562885                  4
4        Tanzania         Africa     1207.520630                  5
..            ...            ...             ...                ...
65          Yemen    Middle East             NaN                  7
66  United States  North America    76657.248884                  1
67         Canada  North America    56256.800726                  2
68      Australia        Oceania    65169.519112                  1
69    New Zealand        Oceania    49099.709042                  2

[70 rows x 4 columns]

In [12]:
pd.read_sql("""
-- Query 8: Compare each country's GDP to its climate-zone average
-- Purpose: Show whether countries are above or below the average GDP of their climate zone.
-- Method: Use AVG() OVER PARTITION BY climate_zone to calculate climate-zone averages.
-- Why: This helps identify outliers and exceptions within each geographic category.

SELECT
    country,
    climate_zone,
    gdp_per_capita,
    AVG(gdp_per_capita) OVER (
        PARTITION BY climate_zone
    ) AS climate_zone_avg_gdp,
    gdp_per_capita - AVG(gdp_per_capita) OVER (
        PARTITION BY climate_zone
    ) AS difference_from_climate_zone_avg
FROM country_metrics
ORDER BY difference_from_climate_zone_avg DESC;
""", conn)

,country,climate_zone,gdp_per_capita,climate_zone_avg_gdp,difference_from_climate_zone_avg
0,Singapore,Tropical,90299.069464,9324.136110,80974.933354
1,Luxembourg,Temperate,123719.658916,49756.872298,73962.786618
2,Ireland,Temperate,105190.685953,49756.872298,55433.813655
3,Qatar,Subtropical,88701.468976,34134.238952,54567.230024
4,Norway,Cold,109269.520580,61303.408166,47966.112415
...,...,...,...,...,...
65,Argentina,Temperate,13962.189409,49756.872298,-35794.682889
66,China,Temperate,12970.605641,49756.872298,-36786.266656
67,Russia,Cold,15619.614258,61303.408166,-45683.793908
68,Taiwan,Subtropical,NaN,34134.238952,NaN
69,Yemen,Tropical,NaN,9324.136110,NaN

In [13]:
pd.read_sql("""
-- Query 9: Countries above sample average GDP per capita
-- Purpose: Identify countries with GDP per capita above the sample average.
-- Method: Use a subquery to calculate average GDP per capita, then filter countries above it.
-- Why: This helps distinguish higher-income countries from the overall country sample.

SELECT
    country,
    region,
    climate_zone,
    gdp_per_capita,
    hdi_value
FROM country_metrics
WHERE gdp_per_capita > (
    SELECT AVG(gdp_per_capita)
    FROM country_metrics
)
ORDER BY gdp_per_capita DESC;
""", conn)

,country,region,climate_zone,gdp_per_capita,hdi_value
0,Luxembourg,Europe,Temperate,123719.658916,0.930
1,Norway,Europe,Cold,109269.520580,0.961
2,Ireland,Europe,Temperate,105190.685953,0.945
3,Switzerland,Europe,Temperate,94394.510680,0.962
4,Singapore,Asia,Tropical,90299.069464,0.939
5,Qatar,Middle East,Subtropical,88701.468976,0.855
6,United States,North America,Temperate,76657.248884,0.921
7,Iceland,Europe,Cold,76350.455042,0.959
8,Denmark,Europe,Temperate,67781.094094,0.948
9,Australia,Oceania,Subtropical,65169.519112,0.951
10,Netherlands,Europe,Temperate,59123.318556,0.941
11,Canada,North America,Temperate,56256.800726,0.936
12,Israel,Middle East,Subtropical,54949.621556,0.919
13,Sweden,Europe,Cold,54836.890724,0.947
14,Austria,Europe,Temperate,52336.772522,0.916
15,United Arab Emirates,Middle East,Tropical,50759.758923,0.911
16,Belgium,Europe,Temperate,50605.749668,0.937
17,Germany,Europe,Temperate,50506.517964,0.942
18,Finland,Europe,Cold,50440.560225,0.940
19,New Zealand,Oceania,Temperate,49099.709042,0.931
20,Hong Kong,Asia,Tropical,48825.844187,0.952
21,United Kingdom,Europe,Temperate,47057.043229,0.929
22,France,Europe,Temperate,40988.639641,0.903
23,Kuwait,Middle East,Subtropical,39981.769104,0.831
24,Saudi Arabia,Middle East,Subtropical,38510.227621,0.875
25,Brunei,Asia,Tropical,36632.928095,0.829
26,Italy,Europe,Temperate,35653.904210,0.895
27,Malta,Europe,Temperate,35638.886946,0.918
28,South Korea,Asia,Temperate,34822.404840,0.925
29,Japan,Asia,Temperate,34065.643896,0.925
30,Cyprus,Europe,Temperate,33231.042969,0.896
31,Bahrain,Middle East,Subtropical,30470.521928,0.875

In [14]:
pd.read_sql("""
-- Query 10: Countries above sample average HDI
-- Purpose: Identify countries with Human Development Index values above the sample average.
-- Method: Use a subquery to calculate average HDI, then filter countries above it.
-- Why: This helps compare economic prosperity with broader human development outcomes.

SELECT
    country,
    region,
    climate_zone,
    gdp_per_capita,
    hdi_value
FROM country_metrics
WHERE hdi_value > (
    SELECT AVG(hdi_value)
    FROM country_metrics
)
ORDER BY hdi_value DESC;
""", conn)

,country,region,climate_zone,gdp_per_capita,hdi_value
0,Switzerland,Europe,Temperate,94394.510680,0.962
1,Norway,Europe,Cold,109269.520580,0.961
2,Iceland,Europe,Cold,76350.455042,0.959
3,Hong Kong,Asia,Tropical,48825.844187,0.952
4,Australia,Oceania,Subtropical,65169.519112,0.951
5,Denmark,Europe,Temperate,67781.094094,0.948
6,Sweden,Europe,Cold,54836.890724,0.947
7,Ireland,Europe,Temperate,105190.685953,0.945
8,Germany,Europe,Temperate,50506.517964,0.942
9,Netherlands,Europe,Temperate,59123.318556,0.941
10,Finland,Europe,Cold,50440.560225,0.940
11,Singapore,Asia,Tropical,90299.069464,0.939
12,Belgium,Europe,Temperate,50605.749668,0.937
13,Canada,North America,Temperate,56256.800726,0.936
14,New Zealand,Oceania,Temperate,49099.709042,0.931
15,Luxembourg,Europe,Temperate,123719.658916,0.930
16,United Kingdom,Europe,Temperate,47057.043229,0.929
17,Taiwan,Asia,Subtropical,NaN,0.926
18,Japan,Asia,Temperate,34065.643896,0.925
19,South Korea,Asia,Temperate,34822.404840,0.925
20,United States,North America,Temperate,76657.248884,0.921
21,Israel,Middle East,Subtropical,54949.621556,0.919
22,Malta,Europe,Temperate,35638.886946,0.918
23,Austria,Europe,Temperate,52336.772522,0.916
24,United Arab Emirates,Middle East,Tropical,50759.758923,0.911
25,Spain,Europe,Temperate,30319.498720,0.905
26,France,Europe,Temperate,40988.639641,0.903
27,Cyprus,Europe,Temperate,33231.042969,0.896
28,Italy,Europe,Temperate,35653.904210,0.895
29,Bahrain,Middle East,Subtropical,30470.521928,0.875
30,Saudi Arabia,Middle East,Subtropical,38510.227621,0.875
31,Portugal,Europe,Temperate,24620.519759,0.866
32,Chile,Latin America,Temperate,15405.616577,0.855
33,Qatar,Middle East,Subtropical,88701.468976,0.855
34,Argentina,Latin America,Temperate,13962.189409,0.842
35,Kuwait,Middle East,Subtropical,39981.769104,0.831
36,Brunei,Asia,Tropical,36632.928095,0.829
37,Russia,Europe/Asia,Cold,15619.614258,0.822
38,Thailand,Asia,Tropical,6909.352818,0.800
39,China,Asia,Temperate,12970.605641,0.768
40,Mexico,Latin America,Subtropical,11405.794047,0.758
41,Brazil,Latin America,Tropical,9281.332821,0.754

## SQL Takeaways

The SQL analysis reinforced several findings from the Python EDA:

- Europe had the highest average GDP per capita.
- Countries with above-average GDP generally exhibited above-average HDI.
- Climate zones displayed meaningful variation in economic outcomes.
- Regional rankings highlighted significant differences within continents.

These SQL findings were incorporated into the broader analysis and modeling sections.